client:
  workload:
    - rps: 10
      duration: 10s
  rq_timeout: 1s
  target_server:
    address: 0.0.0.0
    port: 9002
server:
  profile:
    - rq_latency: 200ms
      duration: 2s
    - rq_latency: 400ms
      duration: 2s
    - rq_latency: 600ms
      duration: 2s
    - rq_latency: 800ms
      duration: 10s
  listen_port: 9002
  threads: 4
