clients:
  - workload:
    - rps: 100
      duration: 10s
    - rps: 480
      duration: 3s
    - rps: 100
      duration: 8s
    rq_timeout: 3s
    retry: 
      count: 3
      factor: 2
      base: 1s
      maxinterval: 5s
    target_server:
      address: 127.0.0.1
      port: 9002
servers:
  - profile:
    - duration: 20s
      latency_distribution:
      - weight: 50
        latency: 20ms
    listen_port: 9002
    threads: 10