clients:
  - workload:
    - rps: 100
      duration: 10s
    - rps: 500
      duration: 3s
    - rps: 100
      duration: 8s
    rq_timeout: 3s
    retry_count: 1
    target_server:
      address: 127.0.0.1
      port: 9002
servers:
  - profile:
    - duration: 20s
      latency_distribution:
      - weight: 50
        latency: 20ms
    listen_port: 9002
    threads: 10