client:
  workload:
    - rps: 10
      duration: 10s
    - rps: 50
      duration: 10s
  rq_timeout: 5s
  target_server:
    address: 0.0.0.0
    port: 9001
server:
  profile:
    - rq_latency: 200ms
      duration: 20s
  listen_port: 9002
  threads: 4
