clients:
  - workload:
    - rps: 2000
      duration: 20s
    - rps: 3000
      duration: 10s
    - rps: 2000
      duration: 30s
    rq_timeout: 500s
    retry_count: 2
    target_server:
      address: 127.0.0.1
      port: 9001
servers:
  - profile:
    - duration: 60s
      latency_distribution:
      - weight: 5
        latency: 3ms
    listen_port: 9002
    threads: 8
