client:
  workload:
    - rps: 100
      duration: 500us
    - rps: 500
      duration: 30ms
  rq_timeout: 100ms
  target_server:
    address: 0.0.0.0
    port: 9001
server:
  profile:
    - rq_latency: 1s
      duration: 5s
    - rq_latency: 500ms
      duration: 4s
    - rq_latency: 250ms
      duration: 5s
    - rq_latency: 125ms
      duration: 4s
  listen_port: 9002
  threads: 4
