client:
  workload:
    - rps: 5000
      duration: 10s
    # 10
    - rps: 5000
      duration: 1s
    - rps: 5100
      duration: 1s
    - rps: 5200
      duration: 1s
    - rps: 5300
      duration: 1s
    - rps: 5400
      duration: 1s
    # 15
    - rps: 5500
      duration: 1s
    - rps: 5600
      duration: 1s
    - rps: 5700
      duration: 1s
    - rps: 5800
      duration: 1s
    - rps: 5900
      duration: 1s
    # 20
    - rps: 6000
      duration: 1s
    - rps: 6100
      duration: 1s
    - rps: 6200
      duration: 1s
    - rps: 6300
      duration: 1s
    - rps: 6400
      duration: 1s
    # 25
    - rps: 6500
      duration: 25s
    # 30
  rq_timeout: 1s
  target_server:
    address: 0.0.0.0
    # port: 9002
    port: 9001
server:
  profile:
    - duration: 50s
      latency_distribution:
      - weight: 90
        latency: 1ms
      - weight: 5
        latency: 4ms
      - weight: 3
        latency: 6ms
      - weight: 1
        latency: 8ms
      - weight: 1
        latency: 16ms
  listen_port: 9002
  threads: 8
