client:
  workload:
    - rps: 10
      duration: 10s
    - rps: 50
      duration: 10s
  rq_timeout: 5s
  target_server:
    address: 0.0.0.0
    port: 9001
server:
  profile:
    - duration: 20s
      - weight: 50
        latency: 200ms
      - weight: 50
        latency: 400ms
  listen_port: 9002
  threads: 4
