clients:
  - workload:
    - rps: 2000
      duration: 60s
    rq_timeout: 500s
    retry_count: 2
    target_server:
      address: 127.0.0.1
      port: 9001
        # - workload:
        #   - rps: 800
        #     duration: 35s
        #   rq_timeout: 500s
        #   target_server:
        #     address: 0.0.0.0
        #     port: 9001
        # - workload:
        #   - rps: 800
        #     duration: 35s
        #   rq_timeout: 500s
        #   target_server:
        #     address: 0.0.0.0
        #     port: 9001
servers:
  - profile:
    - duration: 20s
      latency_distribution:
      - weight: 5
        latency: 3ms
    - duration: 10s
      latency_distribution:
      - weight: 5
        latency: 10ms
    - duration: 30s
      latency_distribution:
      - weight: 5
        latency: 3ms
    listen_port: 9002
    threads: 8
