clients:
  - workload:
    - rps: 200
      duration: 20s
    - rps: 360
      duration: 1s
    - rps: 200
      duration: 9s
    rq_timeout: 500s
    retry_count: 0
    target_server:
      address: 127.0.0.1
      port: 9002
servers:
  - profile:
    - duration: 30s
      latency_distribution:
      - weight: 50
        latency: 3ms
      - weight: 5
        latency: 5ms
      - weight: 5
        latency: 7ms
      - weight: 5
        latency: 10ms
      - weight: 5
        latency: 15ms
      - weight: 5
        latency: 22ms
      - weight: 5
        latency: 34ms
      - weight: 5
        latency: 51ms
      - weight: 5
        latency: 76ms
      - weight: 5
        latency: 115ms
      - weight: 5
        latency: 150ms
    listen_port: 9002
    threads: 8
